### ISSUE TITLE
ANLAB GO-LIVE CHECKLIST

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Anlab#563]
- [x] Enable Google Authentication
- [x] Enable sending emails
- [x] Make sure jobs are all scheduled to run regularly
- [x] Update blob storage location to production space
- [x] Cybersource update to production endpoints
- [x] Sloth update to production endpoints
- [x] Ensure Sloth production is ready to go
- [x] CNAME for anlab.ucdavis.edu
- [x] Make sure only uppercase accounts happen
- [x] Search code for resolveuid (Bad links)
